# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.PositiveIntegerField(choices=[(0, 'Inactive'), (2, 'Active')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('state', models.PositiveIntegerField(choices=[(0, 'ToDo'), (1, 'Doing'), (2, 'Done')], default=2)),
                ('priority', models.PositiveIntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=2)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
